### ISSUE TITLE
[-] Remove Background effects from the sprint mode, keeping a black background even with BGs enabled (too distracting, sprint mode requires precise inputs and concentration)

### ISSUE THREAD

**Issue by Fab052** [Team-Blanker/Aquamino#20]

**Comment by Johang727** [comment]
I see your point, but some players, like myself, prefer a background and effects, even in sprint. I say keep the way it is now and maintain the option to toggle it in the settings.

**Comment by Fab052** [comment]
> I see your point, but some players, like myself, prefer a background and effects, even in sprint. I say keep the way it is now and maintain the option to toggle it in the settings.

I have a better idea anyway. Instead of removing implemented stuff, add some buttons to easily access the settings from the in-game pause menu

**Comment by Fab052** [comment]
the background is less distracting now, so i'm marking this as solved
