### ISSUE TITLE
[Fix] T-Spin Single sends 1 line instead of 2, T-Spin Double sends 3 lines instead of 4 and T-Spin Triple sends 5 lines instead of 6

### ISSUE THREAD

**Issue by Fab052** [Team-Blanker/Aquamino#33]

**Comment by Fab052** [comment]
> Then what's the point of doing T-Spin if they become weak?

it's a simple fix ig

**Comment by Supergamerrr** [comment]
oh, i'm an idiot. i read it wrong. sorry, i'm not a native english speaker. ;(

**Comment by Aqua6623** [comment]
I just weakened T-spins, this is my purpose.
T-spins send less amount of garbage but with more messiness.

**Comment by Aqua6623** [comment]
Closed.
