### ISSUE TITLE
[+] Add "Invisible" mode from Tetris Ultimate (3DS)

### ISSUE THREAD

**Issue by Fab052** [Team-Blanker/Aquamino#39]
This gamemode is kinda obscure, I sent you the video on that mode on discord

Every time you place a tetromino, you'll see all the tetrominoes for x ms before going invisible. When the player levels up, the time in ms will shorten

It's basically a marathon with this "invisible" tweak

edit: found a video, look it up

https://www.youtube.com/watch?v=TQ32xepInMM

**Comment by Aqua6623** [comment]
Closed.
I now have a crazier idea.
